### ISSUE TITLE
Issues connecting TaxJar account in Dokan

### ISSUE THREAD

**Issue by TPP-Chris** [ThePluginPros/marketplace-taxes#15]
In Dokan when attempting to disconnect/reconnect the admin account with both the live and sandbox tokens, it doesn't seem to be connecting.  I tested with both the marketplace and vendor set as the seller of record.

I've tried deactivating/reactivating Marketplace Taxes, and the issue persists.  On the Dokan site, there is no indication of the API connection failure, only a message confirming our settings have been saved.

**Comment by bporcelli** [comment]
Thanks, Chris. I think this might be happening because sandbox/test mode is enabled in wp-config.php. I'll investigate ASAP.

**Comment by bporcelli** [comment]
@TPP-Chris The account is appearing in TaxJar now that sandbox mode is disabled, but it looks like TJ is encountering an error when attempting to pull the transactions:

![linked-account-error](https://user-images.githubusercontent.com/5545098/57197477-b3ae3880-6f35-11e9-9cce-957fbbb01561.png)

I will investigate and open separate issues as needed.

**Comment by TPP-Chris** [comment]
Good deal!  I'll be off work tomorrow as well, with the oldest kid in
school most of the morning.  Let me know if there is anything I can do to
help on the testing/troubleshooting.  I should be free this evening as well
as tomorrow morning to sit down and take a look at it.
