### ISSUE TITLE
Dokan JS error when running MarketShip

### ISSUE THREAD

**Issue by TPP-Chris** [ThePluginPros/marketplace-taxes#18]
When running both Marketship and Marketplace Taxes, and selecting live rates along with another shipping method, the following JS error appears:

![error with multiple methods](https://user-images.githubusercontent.com/46163127/57204561-9f465c00-6f86-11e9-8768-a2544f88a379.JPG)

**Comment by bporcelli** [comment]
Can you please specify where the error appears and when? Thanks.

**Comment by pbmang** [comment]
It's a little sneaky, but it's on this page: https://dokan.thepluginpros.com/dashboard/settings/shipping/ (logged in as a vendor).  When the page opens, there is only the deprecated warning showing.  But, as soon as you click any of the shipping method toggles, the JS error pops up.

**Comment by bporcelli** [comment]
Thanks for the clarification!
