### ISSUE TITLE
Upload transactions to TaxJar directly

### ISSUE THREAD

**Issue by bporcelli** [ThePluginPros/marketplace-taxes#25]
We should upload all transactions to TaxJar ourselves rather than relying on TaxJar to import the transactions every 24 hours. We're already uploading all refunds to TaxJar, so it makes sense to take care of orders as well. This should make for easier testing and a more consistent and reliable user experience.

**Comment by TPP-Chris** [comment]
That sounds like a solid idea!  I'm guessing it would just be done via a
cron with an interval of "x" mins/hours?

**Comment by bporcelli** [comment]
I'm glad you're on board! We can either do this with a cron or upload transactions "on demand" as orders are completed.

**Comment by TPP-Chris** [comment]
I think uploading as orders are completed would be nice for testing purposes, but I'd worry about the potential resource usage for a busy marketplace.  I'd hate to have a busy marketplace have their performance suffer from a constant stream of individual order uploads.  Or, is the amount of data being passed so insignificant that it really wouldn't matter?

**Comment by bporcelli** [comment]
It would be done in the background using the action scheduler / queue built in to newer versions of Woo. Really shouldn't impact performance at all.
