### ISSUE TITLE
Dokan Shipping Error when MT Activated

### ISSUE THREAD

**Issue by pbmang** [ThePluginPros/marketplace-taxes#27]
When MT is activated, but MarketShip is not, the following errors are being thrown on the cart and checkout pages in Dokan:

Notice: Undefined index: seller_id in /home/176304.cloudwaysapps.com/sbdqctjyuq/public_html/wp-content/plugins/dokan-pro/includes/shipping-gateway/vendor-shipping.php on line 394

Notice: Undefined index: seller_id in /home/176304.cloudwaysapps.com/sbdqctjyuq/public_html/wp-content/plugins/dokan-pro/includes/shipping-gateway/shipping.php on line 110

Notice: Undefined index: seller_id in /home/176304.cloudwaysapps.com/sbdqctjyuq/public_html/wp-content/plugins/dokan-pro/includes/wc-functions.phpon line 1048

When I deactivate MT, the errors go away, and Dokan shipping works.  Activating MarketShip along with MT also takes care of this error.  

This seems to only be related to Dokan, and not WCV.

**Comment by pbmang** [comment]
Hey man, looks like I'm still running into issues on the Dokan side.  With MT active, and Dokan shipping disabled, I'm getting these two errors on the cart/checkout pages:

(appears above the items in the cart)
Notice: Undefined index: seller_id in /home/176304.cloudwaysapps.com/sbdqctjyuq/public_html/wp-content/plugins/dokan-pro/includes/shipping-gateway/vendor-shipping.php on line 394

(in the shipping amount area)
Undefined index: seller_id in /home/176304.cloudwaysapps.com/sbdqctjyuq/public_html/wp-content/plugins/dokan-pro/includes/wc-functions.php on line 1048

When I activate the Dokan shipping module, those errors remain, and this one is also added above the items in the cart:

Undefined index: seller_id in /home/176304.cloudwaysapps.com/sbdqctjyuq/public_html/wp-content/plugins/dokan-pro/includes/shipping-gateway/shipping.php on line 110

I tested in incognito mode, purged my cache as well as set cloudflare in development mode and made sure we didn't have Varnish running on the server.  

I left the dokan test site up, if you wanted to take a peek there, but I did change the "admin" user's password to: &9!gqNBJCzzn3SmrRxIQ9wPd after our latest adventure.  

Let me know if I need to check something, or if I have something mis-configured!

**Comment by bporcelli** [comment]
Hey man, something is definitely up. I tested with all supported platforms
yesterday and didn't have a single issue with getting through checkout or
having shipping calculated.

**Comment by pbmang** [comment]
I can spin up a fresh Dokan install this evening and test there as well, to see if maybe something else is going on with the current install.

**Comment by bporcelli** [comment]
@pbmang It turns out that my solution only worked for cases where products from two or more vendors were in the cart. I think I got it now. Here's a new RC for testing: [marketplace-taxes-1.1.4-rc.2.zip](https://github.com/ThePluginPros/marketplace-taxes/files/3562581/marketplace-taxes-1.1.4-rc.2.zip)

Thanks!

**Comment by pbmang** [comment]
@bporcelli solid catch!  I didn't even consider that.  I just did a fair amount of testing, and looks like this one is fixed!  I'm going to jump on WCV now.
