### ISSUE TITLE
Orders Duplicated on Customers "My Account" Order Page

### ISSUE THREAD

**Issue by pbmang** [ThePluginPros/marketplace-taxes#31]
When MT is active, and a customer makes a purchase, if they have an account on the website, when they visit site.com/my-account/orders there will be two entries for each order.  The first entry will show the order status as complete, and the second entry will show the order as Processing.  This is in relation to the ticket in Zoho, and I've also been able to replicate this issue on the WCV.  I am not able to replicate the issue in Dokan, so I think it's unique to WCV.

**Comment by bporcelli** [comment]
Are you sure this has to do with Marketplace Taxes? I don't create orders
or commissions anywhere in the code.

**Comment by pbmang** [comment]
Yeah, it's super weird, but when I deactivate MT, the issue goes away.  I'm
not sure if it helps, or sets off any light bulbs, but when the duplicate
order is created, it's set to a status of "Complete" while the other is set
to "Processing."

**Comment by bporcelli** [comment]
Thanks man, I was ultimately able to fix this. In the process I also discovered some other issues that have crept in over the last few WooCommerce updates. I'll send over an email with the details and an RC.
