### ISSUE TITLE
Discontinue Support Due to Tax Jar Pricing

### ISSUE THREAD

**Issue by pbmang** [ThePluginPros/marketplace-taxes#39]
Tax Jar has raised the price to access the smart calcs API to $299/month. Due to this, adoption is expected to be non-existent, so it’s probably a good time to discontinue support.

**Comment by fastdivision** [comment]
@bporcelli I’ve been following marketplace-taxes for awhile. We’d like to continue to support your integration and provide affordable pricing for WooCommerce marketplaces.

Please reach out to our Partnerships team and apply to become a Technology Partner: https://www.taxjar.com/partners/technology-partner-signup/

I will make sure we get this figured out. Thank you for all of your hard work building out an integration with TaxJar.

**Comment by bporcelli** [comment]
Thanks @fastdivision. Your offer to provide affordable pricing for Marketplace Taxes users is very much appreciated, but we have decided to move forward with discontinuing Marketplace Taxes. The plugin has never achieved the adoption we were hoping for and we would like to focus on other projects.

We will officially end support for Marketplace Taxes on August 21, 2020. We are advising users to act as the seller of record for their marketplace and use the official TaxJar for WooCommerce plugin as an alternative.

Thanks again!
